@startuml
hide footbox
autonumber "<b>[0]"
skinparam monochrome true

actor User
participant SearchService

activate User
User -> SearchService: Delete my filter

activate SearchService
SearchService -> SearchService: Checking filter
SearchService --> User: Confirms filter is deleted

@enduml
