@startuml
hide footbox
autonumber "<b>[0]"
skinparam monochrome true

actor Admin
participant ReportsService

activate Admin
Admin -> ReportsService: see user reports

activate ReportsService
ReportsService -> ReportsService: Checking user reports
ReportsService --> Admin: Something is wrong


@enduml
