@startuml 
hide footbox
autonumber "<b>[0]"
skinparam monochrome true

actor User
participant Userservice

activate User
User -> Userservice: Change password

activate Userservice

Userservice -> Userservice: Changing password
Userservice --> User: Password is changed

@enduml