@startuml 
hide footbox
autonumber "<b>[0]"
skinparam monochrome true

actor User
participant Userservices

activate User
User -> Userservice: Restore my password

activate Userservice
Userservice -> Userservice: Checking for User
Userservice --> User: Password is restored

@enduml